# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.25.1
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
vector = np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
vector.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
vector = np.zeros(10)
vector[4] = 1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
vector = np.arange(50)
vector = vector[::-1]
vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
matrix = np.arange(9).reshape(3, 3)
matrix
# help(np.matrix)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
arr = [1, 2, 0, 0, 4, 0]
new_arr = [x for x in arr if x != 0]
new_arr

[1, 2, 4]

#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
identity_matrix = np.eye(3)

identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [28]:
random_matrix = np.random.random((3, 3, 3))
random_matrix

array([[[0.20278615, 0.18220014, 0.65784422],
        [0.22731653, 0.14556314, 0.86161066],
        [0.37917862, 0.49680472, 0.18000147]],

       [[0.91482209, 0.76165962, 0.19222099],
        [0.37762999, 0.11862334, 0.89835526],
        [0.28116941, 0.12497929, 0.96138679]],

       [[0.09017651, 0.7413018 , 0.92768552],
        [0.73807153, 0.37015533, 0.41390322],
        [0.13445384, 0.65895513, 0.38682377]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [29]:
arr = np.random.random((10, 10))
arr_min, arr_max = arr.min(), arr.max()
arr_min, arr_max

(0.003189154128295235, 0.9895110121619732)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [30]:
arr = np.random.random(30)
arr_mean = arr.mean()
arr_mean


0.4532776195514305

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [22]:
arr = np.zeros((10, 10))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=1)
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [25]:
arr = np.ones((10, 10))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

True

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [29]:
mat = np.zeros((5,5),dtype=int)
np.fill_diagonal(mat[1:], [1,2,3,4])


mat

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [2]:
import numpy as np
mat = np.random.random_integers(0,100,(6,7,8))
# mat
# it is like 7*8 = 56 and now you need the 44th element in the second matrix so 1,6,4
print(mat[1,5,4])
x = np.take(mat,100)
print(x)

31
31


C:\Users\Ron Tohar\AppData\Local\Temp\ipykernel_19760\3869273870.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 100 + 1) instead
  mat = np.random.random_integers(0,100,(6,7,8))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [6]:
mat = np.random.randint(0,101,(5,5))
mat

array([[45, 21, 64, 12,  0, 84, 15, 88],
       [32, 36, 65, 54, 94, 29, 28, 53],
       [39, 21, 48, 42, 39, 38, 30,  3],
       [ 9, 48, 88, 69,  8, 99,  9, 73],
       [22, 72, 82, 88, 30,  8, 87, 79],
       [18, 42, 75, 98,  3, 18, 23, 69],
       [46,  2, 59, 61,  5, 65, 91, 49],
       [ 4, 46, 84, 46, 55, 51, 37, 44]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [12]:
mat = np.random.randint(0,101,(5,5))
print(mat)
normalization = np.linalg.norm(mat)
print(mat/normalization) # one way of normalizing (the other is to transfer each number to a [0,1] interval)

[[97 83 52 11 89]
 [70 80 89 88  2]
 [60 89 68 61 59]
 [29 94 80 64 40]
 [18 46 30 17 72]]
[[0.29523542 0.25262412 0.15827053 0.03348031 0.27088611]
 [0.21305649 0.24349313 0.27088611 0.26784244 0.00608733]
 [0.18261985 0.27088611 0.20696916 0.18566351 0.17957618]
 [0.08826626 0.28610443 0.24349313 0.1947945  0.12174656]
 [0.05478595 0.14000855 0.09130992 0.05174229 0.21914382]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [13]:
mat1 = np.random.randint(0,101,(5,3))
mat = np.random.randint(0,101,(3,2))

new_mat = np.matmul(mat1,mat)
new_mat

array([[10754, 11242],
       [ 4134,  6696],
       [ 5508,  3932],
       [ 5120,  6132],
       [ 6958,  9162]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [21]:
#9 - sums 1 to 5  and -1
#10 - sums 1 to 5 from 5 to 1

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float)) # min int value why???

nan
0


C:\Users\Ron Tohar\AppData\Local\Temp\ipykernel_19760\3955462897.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Ron Tohar\AppData\Local\Temp\ipykernel_19760\3955462897.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


ValueError: cannot convert float NaN to integer

#### 29. How to round away from zero a float array ? (★☆☆)

In [2]:
def create_array(size, random=True):
    if random:
        return np.random.randint(0,101,size)

#### 30. How to find common values between two arrays? (★☆☆)

In [42]:
arr1 = create_array(50)
arr2 = create_array(50)

arr3 = np.intersect1d(arr1,arr2)
arr3

array([ 4,  5, 10, 11, 22, 25, 34, 35, 58, 62, 71, 80, 84, 86, 87, 91, 93])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [45]:
#probably not
print(np.emath.sqrt(-1))
print(np.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))

1j
nan
False


C:\Users\Ron Tohar\AppData\Local\Temp\ipykernel_19760\4161251075.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
C:\Users\Ron Tohar\AppData\Local\Temp\ipykernel_19760\4161251075.py:4: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [46]:
import numpy as np
import datetime

start_date = datetime.date(2016, 7, 1)
end_date = datetime.date(2016, 8, 1)

all_dates = np.arange(start_date, end_date, datetime.timedelta(days=1))

print(all_dates)

['2016-07-01T00:00:00.000000' '2016-07-02T00:00:00.000000'
 '2016-07-03T00:00:00.000000' '2016-07-04T00:00:00.000000'
 '2016-07-05T00:00:00.000000' '2016-07-06T00:00:00.000000'
 '2016-07-07T00:00:00.000000' '2016-07-08T00:00:00.000000'
 '2016-07-09T00:00:00.000000' '2016-07-10T00:00:00.000000'
 '2016-07-11T00:00:00.000000' '2016-07-12T00:00:00.000000'
 '2016-07-13T00:00:00.000000' '2016-07-14T00:00:00.000000'
 '2016-07-15T00:00:00.000000' '2016-07-16T00:00:00.000000'
 '2016-07-17T00:00:00.000000' '2016-07-18T00:00:00.000000'
 '2016-07-19T00:00:00.000000' '2016-07-20T00:00:00.000000'
 '2016-07-21T00:00:00.000000' '2016-07-22T00:00:00.000000'
 '2016-07-23T00:00:00.000000' '2016-07-24T00:00:00.000000'
 '2016-07-25T00:00:00.000000' '2016-07-26T00:00:00.000000'
 '2016-07-27T00:00:00.000000' '2016-07-28T00:00:00.000000'
 '2016-07-29T00:00:00.000000' '2016-07-30T00:00:00.000000'
 '2016-07-31T00:00:00.000000']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [50]:
array = np.random.random((5))*100
array

array1 = [int(x) for x in array]
array2 = np.floor(array)
array3 = np.trunc(array)
array4 = array.astype(int)

print(array1)
print(array2)
print(array3)
print(array4)


[14, 18, 83, 81, 34]
[14. 18. 83. 81. 34.]
[14. 18. 83. 81. 34.]
[14 18 83 81 34]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [58]:
def gen(count, start, end):
    for _ in range(count):
        yield np.random.randint(start, end)

arr = np.array([*gen(10,0,10)])
arr2 = np.fromiter(gen(10,0,10),dtype=int)
print(arr2)
arr

[8 7 2 2 2 8 9 7 1 9]


array([9, 4, 9, 2, 0, 3, 5, 1, 8, 5])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [60]:
arr = create_array(10)
arr = np.sort(arr)
arr

array([ 5, 22, 25, 33, 34, 58, 61, 66, 75, 80])

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [64]:
arr1 = create_array(10)
arr2 = create_array(10)
print(np.array_equal(arr1,arr1))
np.array_equal(arr1,arr2)



True


False

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [79]:
mat = np.array([create_array(2) for k in range(10)])
x, y = mat[:, 0], mat[:, 1]
r = np.sqrt(x**2 + y**2)
print(r)
theta = np.arctan2(y, x)
polar = np.column_stack((r,theta))
polar

[ 69.0651866   11.70469991  86.3539229   77.66595136  73.10950691
  33.54101966  78.64477096  79.92496481 102.95630141  93.62157871]


array([[6.90651866e+01, 4.34508954e-02],
       [1.17046999e+01, 3.48771004e-01],
       [8.63539229e+01, 4.94725682e-01],
       [7.76659514e+01, 1.36330010e+00],
       [7.31095069e+01, 1.51605655e+00],
       [3.35410197e+01, 4.63647609e-01],
       [7.86447710e+01, 8.48377826e-01],
       [7.99249648e+01, 1.01750200e+00],
       [1.02956301e+02, 1.15059961e+00],
       [9.36215787e+01, 1.16450202e+00]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
dtype = [('x', 'int'), (

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [86]:
print("Integer types:")
for dtype in [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64]:
    info = np.iinfo(dtype)
    print(f"min={info.min}, max={info.max}")

# Floating-point types
print("\nFloating-point types:")
for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype}: min={info.min}, max={info.max}")

Integer types:
min=-128, max=127
min=-32768, max=32767
min=-2147483648, max=2147483647
min=-9223372036854775808, max=9223372036854775807
min=0, max=255
min=0, max=65535
min=0, max=4294967295
min=0, max=18446744073709551615

Floating-point types:
<class 'numpy.float16'>: min=-65504.0, max=65504.0
<class 'numpy.float32'>: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
<class 'numpy.float64'>: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [96]:
value = 5
x = create_array(10)
print(x)
closest_val_index = np.argmin(np.absolute(x-value))
x[closest_val_index]

[87 25 68 51 97 29  6 43 27 19]


6

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [106]:
arr = create_array((100))
arr2 = create_array((100))
coordinates =  np.column_stack((arr,arr2))
diff_coordinates = np.diff(coordinates, axis=0)
distances = np.linalg.norm(diff_coordinates, axis=1) # same as root of sum of squares

print("Original coordinates:")
print(coordinates)
print("\nDifferences between consecutive tuples:")
print(diff_coordinates)
print("\nDistances between consecutive tuples:")
print(distances)


Original coordinates:
[[ 6 38]
 [13 46]
 [53 44]]

Differences between consecutive tuples:
[[ 7  8]
 [40 -2]]

Distances between consecutive tuples:
[10.63014581 40.04996879]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
# idk

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [107]:
size = (5,5)
arr = np.array(np.random.normal(size=size))
arr

array([[ 0.39556148,  0.66204569, -0.68133304, -0.02004657, -0.21420549],
       [ 0.16590826,  0.3115608 , -0.04252739, -1.07892588,  1.51675068],
       [ 0.60134054,  0.38492007,  1.41776096,  0.80216564, -0.59527182],
       [ 0.26993879,  0.34806391,  0.41117927,  0.49132804,  0.54540608],
       [-0.03022833, -0.3475099 ,  1.08599026, -2.23633379,  0.87037672]])

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [113]:
arr = create_array((5,2))
rows_mean  = np.mean(arr,1,keepdims=True)
print(arr)
print(rows_mean)
print(arr-rows_mean)

[[46 99]
 [26 54]
 [21 59]
 [70  0]
 [ 5 59]]
[[72.5]
 [40. ]
 [40. ]
 [35. ]
 [32. ]]
[[-26.5  26.5]
 [-14.   14. ]
 [-19.   19. ]
 [ 35.  -35. ]
 [-27.   27. ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [117]:
arr = np.array([1,5,0])-np.array([1,2])
arr

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [17]:
import numpy as np
array = np.array([[1, 2, 0],
                   [4, 5, 0],
                   [7, 8, 0]])

nulls = np.all(array == 0,0) # logical and over the 0 axis (means that for each column, a logical and of the rows will be applied)
print(nulls)
np.any(nulls)

[False False  True]


True

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [25]:
arr1 = create_array((1,3))
arr2 = create_array((3,1))
iter1 = np.nditer(arr1)
iter2 = np.nditer(arr2)

print(arr1)
sum(iter1)
sum(iter2) 
# what is this question



[[84 13  2]]


99

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [41]:
index_vector = np.array([0,3,4,0])
arr = create_array((5))
print(arr)
print(index_vector)
print(arr[index_vector])
arr[index_vector] = arr[index_vector] + 1
print(arr)

[69 96  8 55 62]
[0 3 4 0]
[69 55 62 69]
[70 96  8 56 63]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [57]:
x = create_array((100,100,3))
unique_colors = np.unique(np.reshape(x,(-1,3)),axis=0)
print(len(unique_colors))

9951


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [71]:
d = create_array((100))
s = (np.array([0,1,2,3,4]),np.array([0,8,22,4,5,25,76])) #assuming no repititions

means = np.array([np.mean(d[x]) for x in s])
means

array([54.2       , 37.14285714])

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [13]:
import numpy as np
d = np.array([1,2,3,4,5])   
d = np.insert(d,range(1,len(d)),0)
np.insert(d,range(1,len(d)),0)

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [25]:
array = np.array([[1,1,1],[2,2,2],[3,3,3]])
array[[0, 1]] = array[[1, 0]]
print(array)

[[1 1 1]
 [2 2 2]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [38]:
C = np.array([0, 1, 1, 2, 2, 3, 4, 4, 4, 4, 5])
A = np.repeat(np.arange(len(C)),C) # HARD
np.bincount(A)

array([ 1,  2,  3,  3,  4,  4,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,
        8,  8,  8,  8,  9,  9,  9,  9, 10, 10, 10, 10, 10])

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [38]:
# didnt succeed myself
Z = np.array([1, 2, 3, 4, 5, 6, 7])

# Length of the desired subarrays
n = 3

# Number of subarrays
m = len(Z) - n + 1

# Create a two-dimensional array
result = Z[np.arange(n) + np.arange(m)[:, None]]

print("Two-dimensional array:")
print(result)





Two-dimensional array:


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [39]:
p0_arr = [(1,1),(2,2), (3,5)]
p1_arr = [(1,2),(3,2), (8,4)]
p = (5,5)

def line_dist(p0,p1,point):
    x1, y1 = p0
    x2, y2 = p1
    x0, y0 = point
    a = y2 - y1
    b = x1 - x2
    c = x2*y1 - x1*y2
    return np.abs(a*x0 + b*y0 + c) / np.sqrt(a**2 + b**2)

x = [line_dist(p0_arr[i],p0_arr[i],p) for i in range(len(p0_arr))]
x






C:\Users\Ron Tohar\AppData\Local\Temp\ipykernel_20484\3123084634.py:12: RuntimeWarning: invalid value encountered in scalar divide
  return np.abs(a*x0 + b*y0 + c) / np.sqrt(a**2 + b**2)


[nan, nan, nan]

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [21]:
import numpy as np
array = np.array([[0,0,0,0,0],
                 [1,1,1,1,1],
                 [2,2,2,2,2],
                 [3,3,3,3,3],
                 [4,4,4,4,4]])
shape = (3,3)
index = (0,1)



x = slice(index[0] - ((shape[0]-1)/2),index[0] + ((shape[0]-1)/2))
y = slice(index[1] - ((shape[1]-1)/2),index[1] + ((shape[0]-1)/2))
# a = np.pad()
# array[x,y]





# def need_padding(index, array):
#     if 0+r <= index[0] <= np.shape(array)[0]-r and 0+r <= index[0] <=  np.shape(array)[1] -r:
#         return True
    
#     return False

# if need_padding(index,array):
#     padded_matrix = np.pad(matrix, pad_width=1, mode='constant', constant_values=0)
#     print(padded_matrix)



-1.0

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [16]:
a = np.eye(4)
np.linalg.matrix_rank(a)

4

#### 83. How to find the most frequent value in an array?

In [31]:
a = np.array([1,2])
a[None]

array([[1, 2]])

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [184]:
# from itertools import product
mat = create_array((10,10))
# cols = np.arange(8)[:,None]
# cols = np.array([0,2]) + cols
# cols = np.array(list(product(cols,cols)))
# print(cols)
# all_blocks = [mat[x:y+1,z:w+1] for [[x,y],[z,w]] in cols]
# all_blocks  

from numpy.lib.stride_tricks import sliding_window_view
shape = (3,3)
v = sliding_window_view(mat,shape)
print(v.shape)
print(mat)
v[0,1]


(8, 8, 3, 3)
[[ 90  21  33  21  96  61  57 100  18  94]
 [ 44  52   0  55  66   8   6  50  69   9]
 [ 41  86  63  14  31  63  14  23  55  24]
 [  8  98  10  53  48  77   5  48   5  89]
 [ 11  76  72   3  26  37  52   1  47  26]
 [ 29  58  19  16  24  78  51  19  80   2]
 [ 66  87  82   9  15  83  18  65  54  91]
 [ 93  65  25  48  25  47  78  94  10  21]
 [ 51  33  19  75  38  53  82  22 100  25]
 [ 41   5  48  13  39  71  47  95  45  99]]


array([[21, 33, 21],
       [52,  0, 55],
       [86, 63, 14]])

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [88]:
sum(np.array([[1,1,1],[2,2,2],[3,3,3]]))

array([6, 6, 6])

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [87]:
p = 3
n = 3
M = np.array([create_array((n,n)) for _ in range(p)])
V = np.array([create_array(n,1) for _ in range(p)])
print(M)
print(V)
print("multi")
print(M*V)
print("sum")
sum(M*V)

[[[ 76  75  46]
  [ 85   6   0]
  [ 45   5  45]]

 [[ 87  87  65]
  [ 75  71  68]
  [ 92  79  43]]

 [[ 92  99  94]
  [ 80  32 100]
  [ 43  89  40]]]
[[97 40 51]
 [10 80  6]
 [92 28 38]]
multi
[[[7372 3000 2346]
  [ 850  480    0]
  [4140  140 1710]]

 [[8439 3480 3315]
  [ 750 5680  408]
  [8464 2212 1634]]

 [[8924 3960 4794]
  [ 800 2560  600]
  [3956 2492 1520]]]
sum


array([[24735, 10440, 10455],
       [ 2400,  8720,  1008],
       [16560,  4844,  4864]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [183]:
# def is_neighbor(row1, col1, row2, col2):
#     row_diff = abs(row1 - row2)
#     col_diff = abs(col1 - col2)
    
#     return max(row_diff, col_diff) == 1 and (row_diff + col_diff) != 0

alive= 1
dead = 0

def get_neighbors(grid, row, col):
    
    num_rows, num_cols = grid.shape
    neighbors = []

    for i in range(row - 1, row + 2):
        for j in range(col - 1, col + 2):
            # Skip the current cell
            if i == row and j == col:
                continue
            # Handle toroidal wrapping
            neighbor_row = (i + num_rows) % num_rows
            neighbor_col = (j + num_cols) % num_cols
            neighbors.append(grid[neighbor_row, neighbor_col])

    return neighbors


def lives(grid,row, col):
    neighbors = get_neighbors(grid,row,col)
    num_alive_neighbors = sum(neighbors) # yes I rely on that this is 1
    if grid[row,col] == alive:
        return num_alive_neighbors >= 2
    return num_alive_neighbors >= 3


# Example usage
grid = np.array([
        [0,0,0],
        [0,1,0],
        [0,0,0]])

all_dead = False
print(grid)
print()
while not all_dead:
    all_dead  =True
    for i in range(len(grid)):
        for j in range(len(grid)):
            if lives(grid,i,j):
                grid[i,j] = 1
                all_dead = False
            else:
                grid[i,j] = 0

    print(grid)
    print()

print("ALL DIED")

[[0 0 0]
 [0 1 0]
 [0 0 0]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]

ALL DIED


In [187]:
from time import time
%%timeit 
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

UsageError: Line magic function `%%timeit` not found.


In [ ]:
from numpy.lib.stride_tricks import sliding_window_view
shape = (3,3)
grid = np.array([
        [0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0],
        ])
v = sliding_window_view(grid,shape)


#### 89. How to get the n largest values of an array (★★★)

In [176]:
np.indices(a)

TypeError: only integer scalar arrays can be converted to a scalar index

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [197]:
from itertools import product
n = 2
V = np.array([create_array(3) for _ in range(n)])
ix = [np.indices(v.shape) for v in V]
ix
V[0].shape
# np.indices((2,3))
# print(V)
# cart = product(*V)
# list(cart)

(3,)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [102]:
Z = create_array((5))
print(Z)
np.power(Z,3)
Z*Z
# np.einsum??

[81 41 99 33  9]


array([6561, 1681, 9801, 1089,   81])

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

(10, 3)

In [165]:
a = np.array([[1,1,1]
     ,[2,2,2],
     [3,3,3],
     [1,1,1]
     ,[2,2,2],
     [3,3,3],
     [1,1,1]
     ,[2,2,5],
     [3,8,3],
     [4,4,4]
     ]
)
mask = np.apply_along_axis(lambda y: ~np.all(y==y[0]), axis=1, arr=a) 
a[mask]

array([[2, 2, 5],
       [3, 8, 3]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

[[4 4 4]
 [5 5 6]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [116]:
a = [[1,1,1]
     ,[2,2,2],
     [3,3,3],
     [1,1,1]
     ,[2,2,2],
     [3,3,3],
     [1,1,1]
     ,[2,2,5],
     [3,8,3],
     [4,4,4]
     ]
np.unique(a,axis=0)

array([[1, 1, 1],
       [2, 2, 2],
       [2, 2, 5],
       [3, 3, 3],
       [3, 8, 3],
       [4, 4, 4]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [159]:
X = np.array([1,2,3])
Y = np.array([3,4,5])
l = np.interp(3,X,Y)
l

5.0

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [164]:
X = create_array((1000))
N = 10000
means = [np.mean(np.random.choice(X,100)) for _ in range(N)]
conf_int = np.percentile(means, [2.5, 97.5])
print(np.mean(X))
conf_int

49.48


array([43.68, 55.35])